config/routes.rb
AutoShop::Application.routes.draw do
  devise_for :users

  resources :anuncios, only: [:create, :edit, :update] do
		member do
			get :delete
			delete "delete" => "anuncios#destroy"
			put "approve" => "anuncios#approve"
		end
	end

  get "loja/principal"

	root to: "loja#principal"

end

app/models/ability.rb
class Ability
	include CanCan::Ability

	def initialize(user)
		if user.role == "admin"
			can [:approve], Anuncio
		end
	end
end

app/models/anuncio.rb
class Anuncio < ActiveRecord::Base
  attr_accessible :ano, :descricao, :modelo, :valor, :marca_attributes, :marca_id

	belongs_to :anunciante, class_name: "User"
	belongs_to :marca

	accepts_nested_attributes_for :marca

	validates_presence_of :modelo, :descricao

	def pertence_ao_anunciante?(anunciante)
		self.anunciante == anunciante
	end

	def self.aprovados
		where aprovado: true
	end
end

app/models/marca.rb
class Marca < ActiveRecord::Base
  attr_accessible :nome
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/anuncios_controller.rb
# encoding: utf-8
class AnunciosController < ApplicationController
	before_filter :authenticate_user!
	before_filter :restrito_por_anunciante, except: :create

	def create
		anuncio = Anuncio.new params_anuncio
		anuncio.anunciante = current_user

		if anuncio.save
			flash[:notice] = "Seu anúncio foi cadastrado."
			redirect_to root_url
		else
			render_cadastro anuncio
		end

	end

	def edit
		@anuncio = Anuncio.find params[:id]
		render_cadastro @anuncio
	end

	def update
		anuncio = Anuncio.find params[:id]
		if anuncio.update_attributes params_anuncio
			flash[:notice] = "Anúncio atualizado."
			redirect_to root_url
		else
			render_cadastro anuncio
		end

	end

	def delete
		@anuncio = Anuncio.find params[:id]
	end

	def destroy
		anuncio = Anuncio.find params[:id]
		
		if anuncio.destroy
			flash[:notice] = "O anúncio foi excluído."
		end

		redirect_to root_path
	end

	def approve
		anuncio = Anuncio.find params[:id]
		authorize! :approve, anuncio

		if anuncio.update_attribute :aprovado, true
			flash[:notice] = "O anúncio foi aprovado."
		end

		redirect_to root_path
	end

private
	def restrito_por_anunciante
		anuncio = Anuncio.find(params[:id])
		is_admin = current_user.role == "admin"

		unless is_admin || anuncio.pertence_ao_anunciante?(current_user)
			flash[:alert] = "Este anúncio não é seu espertinho"
			redirect_to root_path
		end
	end

	def params_anuncio
		parameters = params[:anuncio]
		if parameters[:marca_attributes] && !parameters[:marca_attributes][:nome].empty?
			parameters.delete :marca_id
		else
			parameters.delete :marca_attributes
		end

		parameters
	end
end

app/controllers/application_controller.rb
# encoding: utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
	rescue_from CanCan::AccessDenied, with: :sem_autorizacao

	def render_cadastro(anuncio, template = "anuncios/cadastro")
		render template, locals: {
			anuncio: anuncio,
			marcas: Marca.por_nome
		}
	end

private
	def sem_autorizacao
		redirect_to root_url, alert: "Você não tem autorização para acessar esse recurso"
	end
end

app/controllers/loja_controller.rb
class LojaController < ApplicationController
  def principal
		is_admin = current_user && current_user.role == "admin"
		
		if is_admin
			@anuncios = Anuncio.includes(:anunciante).all
		else
			@anuncios = Anuncio.includes(:anunciante).aprovados
		end

		@anuncio = Anuncio.new { |a| a.build_marca }
		render_cadastro @anuncio, "principal"
  end
end

app/helpers/anuncios_helper.rb
module AnunciosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loja_helper.rb
module LojaHelper
end

app/views/anuncios/_anuncio.html.erb
<tr>
	<td><%= anuncio.modelo %></td>
	<td><%= anuncio.ano %></td>
	<td><%= anuncio.valor %></td>
	<td><%= anuncio.marca && anuncio.marca.nome %></td>
	<td><%= anuncio.descricao %></td>
	<td><%= anuncio.anunciante.nome if anuncio.anunciante %></td>
	<% if user_signed_in? && anuncio.pertence_ao_anunciante?(current_user) %>
		<td><%= link_to "Editar", edit_anuncio_path(anuncio) %></td>
		<td>
			<%= link_to "Excluir", delete_anuncio_path(anuncio), 
					method: :delete, 
					data: { confirm: "Quer realmente excluir #{anuncio.modelo}?" } %>
		</td>
	<% end %>
	<% unless anuncio.aprovado %>
	<td><%= link_to "Aprovar", approve_anuncio_path(anuncio), method: :put %></td>
	<% end %>
</tr>

app/views/anuncios/_form.html.erb
<%= simple_form_for @anuncio || Anuncio.new do |f| %>
	<%= f.error_notification %>

	<div class="form-inputs">
		<%= f.input :modelo %>
		<%= f.simple_fields_for :marca do |m| %>
			<%= m.input :nome, label: "Marca" %>
		<% end %>
		<%= select :anuncio, :marca_id, marcas.map{ |m| [m.nome, m.id] },
					prompt: "ou selecione a marca:" %>
		<%= f.input :descricao %>
		<%= f.input :ano %>
		<%= f.input :valor %>
	</div>

	<div class="form-actions">
		<%= f.button :submit %>
	</div>
<% end %>

app/views/anuncios/cadastro.html.erb
<%= render partial: "anuncios/form", locals: { anuncio: anuncio, marcas: marcas } %>

app/views/anuncios/delete.html.erb
<h1><%= @anuncio.modelo %></h1>
<span><%= number_to_currency @anuncio.valor,
						delimiter: ".",
						separator: ",",
						unit: "R$" %></span>
<h2><%= @anuncio.ano %></h2>
<span><%= @anuncio.descricao %></span>

<br /><br />
<%= link_to "Cancelar", root_path %>

<br />
<%= form_for @anuncio, html: { method: :delete } do |f| %>
	<%= f.submit "Confirmar" %>
<% end %>

app/views/anuncios/edit.html.erb
<%= render partial: "anuncios/form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AutoShop</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	Autenticado como <%= current_user.nome %>,
	<%= link_to "Sair", destroy_user_session_path, method: :delete %>
<% else %>
	<%= link_to "Entrar", new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/loja/principal.html.erb
<p><%= notice %></p>
<p><%= alert %></p>

<% if user_signed_in? %>
	<%= render partial: "anuncios/form", locals: { anuncio: anuncio, marcas: marcas } %>
<% end %>

<table>
	<tr>
		<th>Modelo</th>
		<th>Ano</th>
		<th>Valor</th>
		<th>Marca</th>
		<th>Descrição</th>
		<th>Anunciante</th>
	</tr>
	<%= render @anuncios %>
</table>